### PR TITLE
In-test debugging with TS

### PR DESCRIPTION
**Pull request by obernardovieira**

### CODE REVIEW

**Comment by obernardovieira** [comment]
Yes. But you also need to use the `debug(any transaction happening here)` so truffle stops at a given transaction and gives you the contract's variables values.

**Comment by albertocuestacanada** [comment]
Let's have a session where you show me how to get this to work. It's not so obvious.

**Comment by obernardovieira** [comment]
It has to be obvious enough, so I don't need to explain this to anyone else again :+1: 
did you open the truffle site link ?

**Comment by albertocuestacanada** [comment]
I did read the link, but the fact that we don't use truffle directly, but through a number of scripts makes it a bit difficult to put together.

Currently, when I want to test something I do:
`yarn test <path to test file>`

If I want to debug something in that test doing this won't work:
1. Add the `declare function ...` to test/Whathever.test.ts
2. Add `debug(...)` around some statement on test/Whathever.test.ts
3. Run `yarn test --debug test/Whathever.test.ts`

I've tried more things, but the optimal solution would be for the process above to work. If I need to execute `truffle` directly, I have no idea how to do it anymore (but I'll have to learn again, at some point).

**Comment by obernardovieira** [comment]
ahhhhhh sorry. My fault. Yes. It does not work with the scripts, you have to call `npx truffle test --debug test/Whathever.test.ts`. Everything else is right. I guess I need to improve that. How do you suggest? I was not planning to make the script work with the debug command. It's a bit of pointless extra work. Whenever we want to use the debug, we change the script.

**Comment by obernardovieira** [comment]
Can we merge this, then?

**Comment by albertocuestacanada** [comment]
I still didn't have time to check it, sorry. I'll try to do it over the
weekend.

**Pull request merged**
